project_id = "dgypnfiyudrzhxoucbsc"

[functions.submit-enrollment]
verify_jwt = false

[functions.mpesa-payment]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false
